name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  USE_BAZEL_VERSION: 5.0.0-pre.20211011.2
jobs:
  test-linux:
    runs-on: ubuntu-20.04
    env:
      CC: clang-12
    steps:
      - uses: actions/checkout@v2
      - run: blender --version
      - run: bazelisk test --test_output=errors //test/...
  test-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - run: bazelisk test --test_output=errors //test/...
  test-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: bazelisk test --test_output=errors //test/...
