name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CC: clang-12
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: bazelbuild/setup-bazelisk@v1.0.1
      - uses: actions/checkout@v2
      - run: bazel test //...
