name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  USE_BAZEL_VERSION: 5.0.0-pre.20211011.2
jobs:
  test-linux:
    runs-on: ubuntu-latest
    env:
      CC: clang-12
    steps:
      - uses: actions/checkout@v2
      - run: bazelisk test //...
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: bazelisk test //...
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: bazelisk test //...
